index:
    path: /
    controller: App\Controller\HomeController::index
cartas:
    path: /cartas
    controller: App\Controller\CartasController::index
ciudad:
    path: /ciudad
    controller: App\Controller\CiudadController::index